version: '3.9'

services:
  db:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-list-test
    ports:
      - "25432:5432"
      
  pgadmin:
    container_name: pgadmin-todo-list
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" 